export const TODOTASKDATA = [
  "Shopping",
  "Finish that job",
  "Call mom",
  "Clean the kitchen",
  "Pay bills",
  "Workout",
  "Read a book",
  "Plan vacation",
  "Respond to emails",
  "Feed the cat",
  "Do laundry",
  "Organize closet",
  "Write blog post",
  "Water plants",
  "Prepare dinner",
  "Study JavaScript",
  "Meditate",
  "Fix the sink",
  "Walk the dog",
  "Update resume",
  "Backup photos",
  "Clean the fridge",
  "Grocery shopping",
  "Pay rent",
  "Book doctor appointment",
  "Schedule car service",
  "Declutter desk",
  "Learn a new recipe",
  "Call grandma",
  "Plan weekend trip",
  "Sort mail",
  "Clean bathroom",
  "Charge devices",
  "Reply to messages",
  "Vacuum living room",
  "Check bank balance",
  "Stretch",
  "Finish reading book",
  "Clean windows",
  "Buy birthday gift",
  "Organize files",
  "Write thank-you note",
  "Plan meals",
  "Schedule meetings",
  "Change bed sheets",
  "Take vitamins",
  "Check emails",
  "Pay credit card",
  "Journal for 10 minutes",
  "Update calendar",
  "Shopping",
  "Finish that job",
  "Call mom",
  "Clean the kitchen",
  "Pay bills",
  "Workout",
  "Read a book",
  "Plan vacation",
  "Respond to emails",
  "Feed the cat",
  "Wash the car",
  "Organize the closet",
  "Write in journal",
  "Take out the trash",
  "Buy groceries",
  "Walk the dog",
  "Schedule doctor appointment",
  "Prepare lunch",
  "Water the plants",
  "Update resume",
  "Backup files",
  "Clean the bathroom",
  "Do the laundry",
  "Fix the leaky faucet",
  "Plan weekly meals",
  "Review budget",
  "Study for exam",
  "Check bank statements",
  "Send birthday card",
  "Meditate",
  "Declutter desk",
  "Write blog post",
  "Update calendar",
  "Post on social media",
  "Buy gift",
  "Make dentist appointment",
  "Check tire pressure",
  "Call the bank",
  "Sort old clothes",
  "Print documents",
  "Charge electronics",
  "Organize books",
  "Clean windows",
  "Plan weekend trip",
  "Refill prescriptions",
  "Watch tutorial",
  "Update software",
  "Set monthly goals",
  "Do meal prep",
  "Get a haircut"
];

